/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tbd_proyectofinal;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jesus
 */
public class Fondos extends javax.swing.JFrame {
    int sesID;
    
    /**
     * Creates new form Fondos
     */
    public Fondos(int sesID) {
        initComponents();
        this.sesID = sesID;
        Conexion sql = new Conexion();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rB5 = new javax.swing.JRadioButton();
        rB10 = new javax.swing.JRadioButton();
        rB15 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        labelMensaje = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(490, 330));
        setMinimumSize(new java.awt.Dimension(490, 330));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FONDOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 40, 80, 17);

        rB5.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rB5);
        rB5.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        rB5.setForeground(new java.awt.Color(255, 255, 255));
        rB5.setText("5 Fondos");
        getContentPane().add(rB5);
        rB5.setBounds(30, 90, 80, 23);

        rB10.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rB10);
        rB10.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        rB10.setForeground(new java.awt.Color(255, 255, 255));
        rB10.setText("10 Fondos");
        getContentPane().add(rB10);
        rB10.setBounds(30, 130, 80, 23);

        rB15.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rB15);
        rB15.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        rB15.setForeground(new java.awt.Color(255, 255, 255));
        rB15.setText("15 Fondos");
        rB15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rB15ActionPerformed(evt);
            }
        });
        getContentPane().add(rB15);
        rB15.setBounds(30, 170, 80, 23);

        jButton1.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        jButton1.setText("Añadir fondo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 250, 100, 23);

        jButton2.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        jButton2.setText("Regresar a menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(330, 250, 120, 23);

        labelMensaje.setBackground(new java.awt.Color(0, 0, 0));
        labelMensaje.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(labelMensaje);
        labelMensaje.setBounds(280, 140, 190, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/8-bit-wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 490, 335);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Menu(sesID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Conexion sql = new Conexion();
        if(rB5.isSelected()){
            
            
            sql.update(5, sesID);
            labelMensaje.setText("5 fondos añididos :D");
        }
        else if(rB10.isSelected()){
            sql.update(10, sesID);
            labelMensaje.setText("10 fondos añididos :D");
        }
        else{
            sql.update(15, sesID);
            labelMensaje.setText("15 fondos añididos :D");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rB15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rB15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rB15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fondos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fondos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fondos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fondos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fondos(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelMensaje;
    private javax.swing.JRadioButton rB10;
    private javax.swing.JRadioButton rB15;
    private javax.swing.JRadioButton rB5;
    // End of variables declaration//GEN-END:variables
}
