/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tbd_proyectofinal;

/**
 *
 * @author Mauricio Avitia
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txfUsuarioS = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txfCorreoS = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txfContraseñaS = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txfWarning1 = new javax.swing.JLabel();
        txfWarning2 = new javax.swing.JLabel();
        txfWarning3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setMaximumSize(new java.awt.Dimension(360, 347));
        setMinimumSize(new java.awt.Dimension(360, 347));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel1.setText("Registrate para empezar a jugar!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 306, 22);

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre de usuario:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(67, 50, 117, 14);

        txfUsuarioS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfUsuarioSActionPerformed(evt);
            }
        });
        getContentPane().add(txfUsuarioS);
        txfUsuarioS.setBounds(67, 70, 214, 20);

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Correo:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(67, 119, 45, 14);
        getContentPane().add(txfCorreoS);
        txfCorreoS.setBounds(67, 139, 214, 20);

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(67, 188, 72, 14);

        txfContraseñaS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfContraseñaSActionPerformed(evt);
            }
        });
        getContentPane().add(txfContraseñaS);
        txfContraseñaS.setBounds(67, 208, 214, 20);

        jButton1.setText("Registrase");
        getContentPane().add(jButton1);
        jButton1.setBounds(67, 257, 83, 23);
        getContentPane().add(txfWarning1);
        txfWarning1.setBounds(67, 96, 214, 17);
        getContentPane().add(txfWarning2);
        txfWarning2.setBounds(67, 165, 214, 17);
        getContentPane().add(txfWarning3);
        txfWarning3.setBounds(67, 234, 214, 17);

        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(198, 257, 83, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprites/Fondos/SignUp.gif"))); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(360, 347));
        jLabel5.setMinimumSize(new java.awt.Dimension(360, 347));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 360, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfUsuarioSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfUsuarioSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfUsuarioSActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txfContraseñaSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfContraseñaSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfContraseñaSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txfContraseñaS;
    private javax.swing.JTextField txfCorreoS;
    private javax.swing.JTextField txfUsuarioS;
    private javax.swing.JLabel txfWarning1;
    private javax.swing.JLabel txfWarning2;
    private javax.swing.JLabel txfWarning3;
    // End of variables declaration//GEN-END:variables
}
